In [4]:
import pandas as pd

df = pd.read_csv("../data/financecore_clean.csv")

df.head()

,transaction_id,client_id,date_transaction,montant,devise,taux_change_eur,montant_eur,categorie,produit,agence,...,is_anomaly_score,is_anomaly,year,month,quarter,weekday,montant_eur_verifie,montant_eur_diff,montant_eur_flag,categorie_risque
0,txn000559,cli0060,2022-04-19 02:31:00,2050.42,eur,1.00,2050.42,depot especes,compte epargne,marseille-vieux-port,...,0,0,2022,4,2,1,2050.420000,0.000000,False,medium
1,txn001154,cli0057,2024-06-20 20:51:00,-123.66,gbp,0.86,-143.79,retrait dab,credit consommation,bordeaux-meriadeck,...,0,0,2024,6,2,3,-143.790698,0.000698,False,high
2,txn000764,cli0015,2024-08-28 05:03:00,-396.17,eur,1.00,-396.17,prelevement,pea,lyon-part-dieu,...,0,0,2024,8,3,2,-396.170000,0.000000,False,medium
3,txn001598,cli0045,2024-01-07 08:16:00,225.20,eur,1.00,225.20,paiement cb,credit consommation,bordeaux-meriadeck,...,0,0,2024,1,1,6,225.200000,0.000000,False,low
4,txn001873,cli0034,2024-08-11 19:52:00,935.32,eur,1.00,935.32,interets,credit immobilier,bordeaux-meriadeck,...,0,0,2024,8,3,6,935.320000,0.000000,False,high

In [6]:
print(df["segment_client"].unique())

<StringArray>
['premium', 'risque', 'standard']
Length: 3, dtype: str

In [4]:
print("Nomber dublicated = " , df.duplicated().sum())

Nomber dublicated =  0

In [8]:
print(df["devise"].unique())

<StringArray>
['eur', 'gbp', 'chf', 'usd', 'mad']
Length: 5, dtype: str

In [10]:
print(df["categorie"].unique())

<StringArray>
[         'depot especes',            'retrait dab',            'prelevement',
            'paiement cb',               'interets',   'remboursement credit',
 'virement international',               'virement']
Length: 8, dtype: str

In [11]:
print(df["statut"].unique())

<StringArray>
['complete', 'rejete', 'en attente']
Length: 3, dtype: str

In [6]:
print(df["type_operation"].unique())

<StringArray>
['credit', 'debit']
Length: 2, dtype: str

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1925 entries, 0 to 1924
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       1925 non-null   str
 1   client_id            1925 non-null   str
 2   date_transaction     1925 non-null   str
 3   montant              1925 non-null   float64
 4   devise               1925 non-null   str
 5   taux_change_eur      1925 non-null   float64
 6   montant_eur          1925 non-null   float64
 7   categorie            1925 non-null   str
 8   produit              1925 non-null   str
 9   agence               1925 non-null   str
 10  type_operation       1925 non-null   str
 11  statut               1925 non-null   str
 12  score_credit_client  1925 non-null   float64
 13  segment_client       1925 non-null   str
 14  solde_avant          1925 non-null   float64
 15  taux_interet         1925 non-null   float64
 16  is_anomaly_amount    1925 non-null   int64
 17  is_anomaly_score     1925 non-null   int64
 18  is_anomaly           1925 non-null   int64
 19  year                 1925 non-null   int64
 20  month                1925 non-null   int64
 21  quarter              1925 non-null   int64
 22  weekday              1925 non-null   int64
 23  montant_eur_verifie  1925 non-null   float64
 24  montant_eur_diff     1925 non-null   float64
 25  montant_eur_flag     1925 non-null   bool
 26  categorie_risque     1925 non-null   str
dtypes: bool(1), float64(8), int64(7), str(11)
memory usage: 393.0 KB

In [13]:

df.describe()

,montant,taux_change_eur,montant_eur,score_credit_client,solde_avant,taux_interet,is_anomaly_amount,is_anomaly_score,is_anomaly,year,month,quarter,weekday,montant_eur_verifie,montant_eur_diff
count,1925.000000,1925.000000,1925.000000,1925.000000,1925.000000,1925.0,1925.000000,1925.000000,1925.000000,1925.000000,1925.000000,1925.000000,1925.000000,1925.000000,1925.000000
mean,-228.169356,1.526416,-130.081221,630.700779,24959.617236,0.0,0.054545,0.112727,0.157922,2022.983896,6.466494,2.492468,3.039481,-234.584422,104.503201
std,14610.310271,2.217947,2092.473039,125.442712,14220.138619,0.0,0.227150,0.316341,0.364763,0.812615,3.460731,1.112474,1.995186,14580.415469,14340.198845
min,-200000.000000,0.860000,-8705.810000,-100.000000,103.040000,0.0,0.000000,0.000000,0.000000,2022.000000,1.000000,1.000000,0.000000,-200000.000000,-152349.570000
25%,-1415.140000,1.000000,-1294.510000,591.000000,12590.800000,0.0,0.000000,0.000000,0.000000,2022.000000,3.000000,1.000000,1.000000,-1294.511628,0.000000
50%,-91.030000,1.000000,-73.350000,643.000000,25689.550000,0.0,0.000000,0.000000,0.000000,2023.000000,7.000000,3.000000,3.000000,-66.730000,0.000000
75%,1091.380000,1.000000,963.220000,696.000000,36956.910000,0.0,0.000000,0.000000,0.000000,2024.000000,9.000000,3.000000,5.000000,967.130000,0.000000
max,150000.000000,10.850000,9026.940000,1500.000000,49997.710000,0.0,1.000000,1.000000,1.000000,2024.000000,12.000000,4.000000,6.000000,150000.000000,201401.120000